apiVersion: batch/v1
kind: Job
metadata:
  name: job-test
spec:
  template:
    spec:
      containers:
      - command:
        - sh
        - -c
        - printenv  && echo nouveau salut $GITHUB_TOKEN $test  && sleep 1000
        envFrom:
        - configMapRef:
            name: map-test2
        - secretRef:
            name: githubsecret
        - secretRef:
            name: notionsecret
        image: busybox
        imagePullPolicy: Always
        name: busybox
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Never
  backoffLimit: 4
