{{ range $k, $v := .Values.scripts }}
{{- if $v.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: job-export-ops
spec:
  template:
    spec:
      containers:
      - command:
        - sh
        - -c
        - {{ $v.command }}
        env:
        - name: GLOBAL_RIGHTS_DATABASE_ID
          value: {{ $.Values.database_id.general }}
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              key: GITHUB_TOKEN
              name: {{ $.Values.secret_name.github }}
        - name: NOTION_KEY
          valueFrom:
            secretKeyRef:
              key: NOTION_KEY
              name: {{ $.Values.secret_name.notion }}
        - name: SPECIFIC_RIGHT_DEMO_DATABASE_ID
          value: {{ $.Values.database_id.demo }}
        - name: SPECIFIC_RIGHT_FORMATION_DATABASE_ID
          value: {{ $.Values.database_id.formation }}
        - name: SPECIFIC_RIGHT_PROD_DATABASE_ID
          value: {{ $.Values.database_id.prod }}
        - name: SPECIFIC_RIGHT_STAGING_DATABASE_ID
          value: {{ $.Values.database_id.staging }}
        image: exportops
        imagePullPolicy: Never
        name: export-ops-right
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Never
  backoffLimit: 4

---
{{- end }}
{{- end }}
