name: argo-workflow
run-name: Launching argo-workflow
on:
  push:
jobs:
  job_name:
    runs-on: ubuntu-latest
    steps:
      - name: step_name
        run: >-
             docker run --rm
             -e ARGO_TOKEN="${{ secrets.ARGO_DEV_TOKEN }}"
             -e ARGO_SERVER="${{ secrets.ARGO_DEV_SERVER }}"
             -e ARGO_NAMESPACE="ops-rights-exporter"
             ${{ secrets.DOCKER_ACR_REGISTRY_HOSTNAME }}/padoa-tools/gocd-tools:latest
             bash -c '
                 argo submit --argo-http1 --secure \
                 -n ops-rights-exporter \
                 -s $ARGO_SERVER \ 
                 --token $ARGO_TOKEN \
                 --from workflowtemplate/workflow-template-ops-rights-exporter-rights-by-env \
                 -v
