name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/2 * * * *'
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test"
